### PR TITLE
added Preseason 2018 and Season 2018 to Enums

### PR DESCRIPTION
**Pull request by hemmoleg**

### CODE REVIEW

**Comment by hemmoleg** [comment]
Hey, when will you release a new package version?

**Comment by aj-r** [comment]
Probably today :)

**Review by aj-r — APPROVED** [review]
Thanks for the PR!

**Comment by hemmoleg** [comment]
Thx! :D

**Comment by aj-r** [comment]
I've pushed 6.3.0 to NuGet. Should be available for download soon.

**Pull request merged**
